name: Build OrgPhotos OneDrive Add-on

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build add-on
        uses: home-assistant/addon-builder-action@v1
